### ISSUE TITLE
SDK not getting connected for custom deployment.

### ISSUE THREAD

**Issue by aswinpradeep** [Open-Speech-EkStep/speech-recognition-open-api-client#1]
We were just trying to set up ASR inference server with the latest code from (https://github.com/Open-Speech-EkStep/speech-recognition-open-api). We are able to do inference on it  by using the python example file provided.(examples/python/speech-recognition/main.py).
 As we also want to test the real time inference, we cloned this repo and tried running the react example provided with the custom URL that worked in the above case. But with our hosted endpoint, we get Web socket connection failed error. Does any change need to be done on server/client side to enable socket connection for real time ?

**Comment by ankit-thoughtworks** [comment]
This client is designed to support socket.io clients only and require a socket.io server to serve it. To do the integration with GRPC we have a proxy server https://github.com/Open-Speech-EkStep/speech-recognition-open-api-proxy. You can see the architecture for real-time streaming https://open-speech-ekstep.github.io/asr_streaming_service/

**Comment by Sujit27** [comment]
Thank you, Ankit

**Comment by aswinpradeep** [comment]
fixed, working now
